
CREATE TABLE Artista (
    Id TEXT NOT NULL PRIMARY KEY,
    Nome VARCHAR(256) NOT NULL
)


CREATE TABLE Playlist (
    Id TEXT NOT NULL  PRIMARY KEY,
    Titulo TEXT NOT NULL,
    Created_At TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE  Musica (
    Id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
    Isrc TEXT NOT NULL UNIQUE,
    Nome TEXT NOT NULL,
    Duracao_Em_Segundos INTEGER NOT NULL
    Is_Explicita BOOLEAN

)


